from server.config.database import SQLALCHEMY_DATABASE_URI, SQLALCHEMY_TRACK_MODIFICATIONS
from server.config.jwt import JWT_ACCESS_TOKEN_EXPIRES, JWT_BLACKLIST_ENABLED, JWT_BLACKLIST_TOKEN_CHECKS

DEBUG_MODE = True
SECRET_KEY = '123456789'
