name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker front images
      run: docker-compose build
      - name: Up the Docker front images
      run: docker-compose up
